part of 'platform_routes.dart';

const _externalRoutePathByAlias = {
  'quick-image': AppRoutes.quick,
  'quick': AppRoutes.quick,
  'quick-reply': AppRoutes.quick,
  'quickreply': AppRoutes.quick,
  'image': AppRoutes.image,
  'image-input': AppRoutes.image,
  'imageinput': AppRoutes.image,
  'screenshot': AppRoutes.image,
  'text': AppRoutes.text,
  'text-input': AppRoutes.text,
  'textinput': AppRoutes.text,
  'moments': AppRoutes.moments,
  'moment': AppRoutes.moments,
  'moment-profile': AppRoutes.moments,
  'momentprofile': AppRoutes.moments,
  'profile-image': AppRoutes.moments,
  'history': AppRoutes.history,
  'people': AppRoutes.people,
  'persons': AppRoutes.people,
  'person-library': AppRoutes.people,
  'personlibrary': AppRoutes.people,
  'simulation': AppRoutes.simulation,
  'simulate': AppRoutes.simulation,
  'conversation-simulation': AppRoutes.simulation,
  'conversation-sim': AppRoutes.simulation,
  'training': AppRoutes.simulation,
  'practice': AppRoutes.simulation,
  'people/simulation': AppRoutes.simulation,
  'person-library/simulation': AppRoutes.simulation,
  'simulation/select': AppRoutes.peopleSelectSimulation,
  'simulation/people': AppRoutes.peopleSelectSimulation,
  'simulation/profile': AppRoutes.peopleSelectSimulation,
  'people/select-simulation': AppRoutes.peopleSelectSimulation,
  'people/simulation/select': AppRoutes.peopleSelectSimulation,
  'person-library/select-simulation': AppRoutes.peopleSelectSimulation,
  'add-person': AppRoutes.peopleEdit,
  'addperson': AppRoutes.peopleEdit,
  'new-person': AppRoutes.peopleEdit,
  'newperson': AppRoutes.peopleEdit,
  'people/add': AppRoutes.peopleEdit,
  'people/new': AppRoutes.peopleEdit,
  'person-library/add': AppRoutes.peopleEdit,
  'person-library/new': AppRoutes.peopleEdit,
  'people/edit': AppRoutes.peopleEdit,
  'settings': AppRoutes.settings,
  'personalization': AppRoutes.personalization,
  'personalization-settings': AppRoutes.personalization,
  'personalizationsettings': AppRoutes.personalization,
  'reply-settings': AppRoutes.personalization,
  'style-settings': AppRoutes.personalization,
  'settings/personalization': AppRoutes.personalization,
  'settings/personalization-settings': AppRoutes.personalization,
  'settings/reply-settings': AppRoutes.personalization,
  'settings/style-settings': AppRoutes.personalization,
  'api-settings': AppRoutes.api,
  'apisettings': AppRoutes.api,
  'api': AppRoutes.api,
  'settings/api': AppRoutes.api,
  'settings/api-settings': AppRoutes.api,
  'privacy': AppRoutes.privacy,
  'privacy-settings': AppRoutes.privacy,
  'privacysettings': AppRoutes.privacy,
  'settings/privacy': AppRoutes.privacy,
  'settings/privacy-settings': AppRoutes.privacy,
  'shortcut': AppRoutes.floatingGuide,
  'shortcuts': AppRoutes.floatingGuide,
  'shortcut-guide': AppRoutes.floatingGuide,
  'shortcutguide': AppRoutes.floatingGuide,
  'floating-guide': AppRoutes.floatingGuide,
  'floatingguide': AppRoutes.floatingGuide,
  'floating-window': AppRoutes.floatingGuide,
  'floatingwindow': AppRoutes.floatingGuide,
  'settings/shortcut': AppRoutes.floatingGuide,
  'settings/shortcuts': AppRoutes.floatingGuide,
  'settings/shortcut-guide': AppRoutes.floatingGuide,
  'settings/floating-guide': AppRoutes.floatingGuide,
};

const _externalRouteWrappers = {
  'open',
  'route',
  'router',
  'navigate',
  'navigation',
  'go',
  'screen',
  'page',
  'target',
  'deeplink',
  'url',
  'uri',
  'link',
  'destination',
};

const _externalRouteContainers = {
  'settings',
};

const _externalRouteQueryAliases = {
  'route',
  'path',
  'targetroute',
  'target',
  'screen',
  'page',
  'deeplink',
  'url',
  'uri',
  'link',
  'destination',
};
